"""Regression guard for Docker image tag format rules.

This repository currently produces no image tags itself (CI only runs
tests and creates issues on failure — see .github/workflows/ci.yml).  The
image tags used by the wider pipeline (ghcr.io/rbnbrls/finance-sync:*)
are generated by docker/metadata-action in the finance-sync repository.

These tests pin the Docker tag sanitization contract so that if any
tag-generating code is ever added here (or an inline workflow step starts
deriving a tag), it cannot silently violate the format rules:

  * lowercase only
  * allowed characters: [a-z0-9._-]
  * maximum length: 128 characters

Reference: https://docs.docker.com/engine/reference/commandline/tag/
"""

from __future__ import annotations

import re

# Docker reference component rules (tag portion): lowercase alphanumeric
# plus '.', '_', '-'; max 128 chars.
_TAG_RE = re.compile(r"^[a-z0-9][a-z0-9._-]*$")
_MAX_TAG_LENGTH = 128


def sanitize_image_tag(raw: str) -> str:
    """Normalize a raw value into a valid Docker image tag.

    Mirrors the sanitization applied by docker/metadata-action (and the
    Docker reference spec): lowercases, strips characters outside
    ``[a-z0-9._-]``, collapses runs of invalid separators, and truncates
    to 128 chars.  The result always satisfies :data:`_TAG_RE`.
    """
    lowered = raw.lower()
    cleaned = re.sub(r"[^a-z0-9._-]+", "-", lowered).strip("._-")
    if not cleaned:
        cleaned = "latest"
    return cleaned[:_MAX_TAG_LENGTH].rstrip("._-") or "latest"


class TestDockerTagSanitization:
    """Pin the Docker image tag format rules."""

    def test_valid_tags_are_unchanged(self) -> None:
        # The tags currently emitted by the pipeline (short sha, semver).
        for tag in ("abc1234", "1.2.3", "sha-abc1234", "v1.2.3", "latest"):
            assert _TAG_RE.match(tag), tag
            assert sanitize_image_tag(tag) == tag

    def test_lowercases_uppercase_input(self) -> None:
        assert sanitize_image_tag("MyImage") == "myimage"
        assert sanitize_image_tag("SHA-Abc1234") == "sha-abc1234"

    def test_strips_invalid_characters(self) -> None:
        # Spaces, slashes, colons, and other invalid chars become '-'.
        assert _TAG_RE.match(sanitize_image_tag("release/1.0:beta"))
        assert _TAG_RE.match(sanitize_image_tag("UPPER case! tag"))
        assert _TAG_RE.match(sanitize_image_tag("feat/fix (x)"))

    def test_truncates_to_128_chars(self) -> None:
        long_raw = "a" * 200
        result = sanitize_image_tag(long_raw)
        assert len(result) <= 128
        assert _TAG_RE.match(result)

    def test_empty_and_garbage_input_fall_back_to_latest(self) -> None:
        assert sanitize_image_tag("") == "latest"
        assert sanitize_image_tag("!!!") == "latest"
        assert _TAG_RE.match(sanitize_image_tag("!!!"))

    def test_docker_tag_length_cap_is_128(self) -> None:
        # The spec cap: 128 characters max for a tag component.  The
        # character-class regex alone does not enforce the cap — the
        # truncation in sanitize_image_tag does.
        assert _MAX_TAG_LENGTH == 128
        assert len(sanitize_image_tag("a" * 200)) <= 128
